name: Adaptive CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  smart-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest black flake8
        
    - name: Analyze project structure
      id: analyze
      run: |
        echo "🔍 Анализ структуры проекта..."
        
        # Найти все тестовые файлы
        TEST_FILES=$(find . -name "*test*.py" -type f | grep -v __pycache__ | head -20)
        
        if [ -z "$TEST_FILES" ]; then
          echo "tests_found=false" >> $GITHUB_OUTPUT
          echo "test_path=" >> $GITHUB_OUTPUT
        else
          echo "tests_found=true" >> $GITHUB_OUTPUT
          echo "📁 Найденные тестовые файлы:"
          echo "$TEST_FILES"
          
          # Определить основную папку с тестами
          if [ -d "tests" ] && [ "$(find tests -name "*.py" -type f | wc -l)" -gt 0 ]; then
            echo "test_path=tests/" >> $GITHUB_OUTPUT
            echo "📍 Основная папка тестов: tests/"
          elif [ -f "test_api.py" ]; then
            echo "test_path=test_api.py" >> $GITHUB_OUTPUT
            echo "📍 Тест в корне: test_api.py"
          else
            # Найти первый тестовый файл
            FIRST_TEST=$(echo "$TEST_FILES" | head -1)
            echo "test_path=$FIRST_TEST" >> $GITHUB_OUTPUT
            echo "📍 Первый найденный тест: $FIRST_TEST"
          fi
        fi
        
        # Проверить main.py
        if [ -f "main.py" ]; then
          echo "main_exists=true" >> $GITHUB_OUTPUT
          echo "📄 Найден main.py"
        else
          echo "main_exists=false" >> $GITHUB_OUTPUT
          echo "⚠️  main.py не найден"
        fi
        
    - name: Check code formatting
      run: |
        echo "🔍 Проверка форматирования..."
        if black --check --diff .; then
          echo "✅ Код отформатирован правильно!"
        else
          echo "❌ Код нужно отформатировать"
          echo ""
          echo "🔧 Исправление:"
          echo "  black ."
          echo "  git add ."
          echo "  git commit -m 'Format code with Black'"
          echo "  git push"
          exit 1
        fi
        
    - name: Run linting (warnings only)
      run: |
        echo "🔍 Проверка стиля кода..."
        flake8 . --count --statistics --exit-zero || true
        
    - name: Run tests
      if: steps.analyze.outputs.tests_found == 'true'
      run: |
        echo "🧪 Запуск найденных тестов..."
        echo "📍 Путь к тестам: ${{ steps.analyze.outputs.test_path }}"
        pytest ${{ steps.analyze.outputs.test_path }} -v
        
    - name: No tests warning
      if: steps.analyze.outputs.tests_found == 'false'
      run: |
        echo "⚠️  Тесты не найдены!"
        echo ""
        echo "💡 Рекомендуемая структура:"
        echo "  mkdir tests"
        echo "  # Создать tests/test_api.py с вашими тестами"
        echo "  # Или поместить test_api.py в корень проекта"
        echo ""
        echo "🔍 Поиск Python файлов в проекте:"
        find . -name "*.py" -type f | grep -v __pycache__ | head -10
        
    - name: Test main.py import
      if: steps.analyze.outputs.main_exists == 'true'
      run: |
        echo "🧪 Проверка импорта main.py..."
        python -c "
        try:
            import main
            print('✅ main.py импортируется успешно')
        except Exception as e:
            print(f'❌ Ошибка импорта main.py: {e}')
            exit(1)
        "
        
    - name: Success summary
      run: |
        echo "🎉 Проверки завершены!"
        echo ""
        echo "📊 Результаты:"
        echo "  📄 main.py: ${{ steps.analyze.outputs.main_exists == 'true' && '✅' || '❌' }}"
        echo "  🧪 Тесты: ${{ steps.analyze.outputs.tests_found == 'true' && '✅' || '⚠️' }}"
        echo "  🎨 Форматирование: ✅"
        echo ""
        if [ "${{ steps.analyze.outputs.tests_found }}" == "false" ]; then
          echo "💡 Следующий шаг: добавить тесты"
        else
          echo "🚀 Проект готов к разработке!"
        fi
