name: Backend CI/CD

on:
  pull request:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    container: 
      image: node:20
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:   
        node-version:20
      -run: npm ci
      -run: npm test
      -run: npm run build
